name: git-diff-test

on:
  push:
    branches:
      - dev

jobs:
  jobi-joba: # name of the job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch, for comparison
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: List branches
      run:  git branch -a
    - name: Check teams that changed
      run: echo $(git diff --name-only origin/main...$GITHUB_SHA)
